### ISSUE TITLE
Joomla complains, the db checker complains, JSON checker says it's valid

### ISSUE THREAD

**Issue by MarkRS-UK** [robwent/joomla-json-db-check#10]
Hi,

I have (just found) this problem on my website horsemanshipmagazine.co.uk.
The checker finds hundreds of JSON failures, all in #__content, column attribs (example of the first one below), all syntax errors, and the website is severely broken when a user logs in and accesses anything other than the home page (I think), however the JSON checker (at http://jsonlint.com/) says there's no problem with this one, or any of the others I've tried.

Any idea what's going on?

```
{"show_title":"","link_titles":"","show_intro":"","show_section":0,"link_section":"","show_category":0,"link_category":"","show_vote":"","show_author":0,"show_create_date":0,"show_modify_date":"","show_pdf_icon":"","show_print_icon":"","show_ email_icon":"","language":"","keyref":"","readmore":"","show_parent_category":"","link_parent_category":"","link_author":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":"","show_publishing_options":"","show_article_options":"","show_urls_images_backend":"","show_urls_images_frontend":""}
```

**Comment by MarkRS-UK** [comment]
Ok, I have a working hypothesis.
For the first three I have tried, one of which is above, there is (somehow) a rogue CR(LF?) in the string.
In the above it's at the end of the third line. It's been inserted in show_email_icon.
I've now fixed three rows with the problem.  How did that happen? Can it not be fixed automagically? There surely shouldn't be one of those in any JSON string... should there?

**Comment by MarkRS-UK** [comment]
I think it's moved from hypothesis to theory.

Removing CRs (there were no LFs in my attribs) with an SQL UPDATE (after doing many by hand) has removed the problem.

Incidentally, in one or two cases I saw the checker complained of "incorrect JSON syntax" when the error appeared in fact to be that the user marked as the article creator was no longer on the system.

**Comment by robwent** [comment]
The CRs makes sense, but the script doesn't care whether users are in the system or not, it just checks to see if the string starts with { or ends with } and then checks if it's valid json or not.

**Comment by MarkRS-UK** [comment]
I agree, but it complained about rows that had this as a problem and I couldn't see a specific JSON related problem.

Since CR is illegal in a JSON string according to the spec, couldn't this be fixed by the checker?

Anyway, I'm all done now, fixed :) D'you want me to close this or will you?

Thanks for the checker.

**Comment by retro777** [comment]
Hi, my joomla site error display.
how do i fix this?

Row 5 is not valid JSON. Error: (Syntax error)
Content: {"field_width_type":"percentage","field_width_type-percentage-width":"100","field_width_type-bootstrap-width":"span12"

Row 252 is not valid JSON. Error: (Syntax error)
Content: {"show_base_description":"1","categories_description":"Because this links to the root category the "uncategorised" category is displayed. ","maxLevel":"-1","show_empty_categories":"1","show_description":"1","show_description_image":"1","show_cat_num_articles":"1","display_num":"","show_headings":"","orderby_pri":"","orderby_sec":"","order_date":"","show_pagination":"","show_noauth":"","show_feed_image":"","show_feed_description":"","show_item_description":"","feed_character_count":"0","show_feed_link":"","feed_summary":"","menu-anchor_title":"","menu-anchor_css":"","menu_image":"","show_page_heading":0,"page_title":"","page_heading":"","pageclass_sfx":"","menu-meta_description":"","menu-meta_keywords":"","robots":"","secure":0}

**Comment by robwent** [comment]
Hi, what table did it say it was related to before the rows?

**Comment by retro777** [comment]
maybe this.. please tell me :D

Checking table: seitoubokuyou_ce_cf, column params

Row 5 is not valid JSON. Error: (Syntax error)
Content: {"field_width_type":"percentage","field_width_type-percentage-width":"100","field_width_type-bootstrap-width":"span12"

Checking table: vp0km_menu, column params

Row 252 is not valid JSON. Error: (Syntax error)
Content: {"show_base_description":"1","categories_description":"Because this links to the root category the "uncategorised" category is displayed. ","maxLevel":"-1","show_empty_categories":"1","show_description":"1","show_description_image":"1","show_cat_num_articles":"1","display_num":"","show_headings":"","orderby_pri":"","orderby_sec":"","order_date":"","show_pagination":"","show_noauth":"","show_feed_image":"","show_feed_description":"","show_item_description":"","feed_character_count":"0","show_feed_link":"","feed_summary":"","menu-anchor_title":"","menu-anchor_css":"","menu_image":"","show_page_heading":0,"page_title":"","page_heading":"","pageclass_sfx":"","menu-meta_description":"","menu-meta_keywords":"","robots":"","secure":0}

**Comment by robwent** [comment]
Did you try linting those records so you can fix them?

http://jsonlint.com/

The first one is missing a closing bracket and the menu table the category description needs the quotes escaping.

`the \"uncategorised\" category`

**Comment by retro777** [comment]
oh,,
great!! complete works. thanks
